insert into dbo.locations select LOCATION_ID,STREET_ADDRESS,POSTAL_CODE,CITY,STATE_PROVINCE,COUNTRY_ID from dbo.LOCATIONS_External;
insert into dbo.jobs select JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY from dbo.JOBS_External;
insert into dbo.employees select EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID from dbo.EMPLOYEES_External;
insert into dbo.departments select DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID from dbo.DEPARTMENTS_External;
insert into dbo.countries select COUNTRY_ID,COUNTRY_NAME,REGION_ID from dbo.COUNTRIES_External;
insert into dbo.PROMOTIONS select PROMO_ID,PROMO_NAME from dbo.PROMOTIONS_External;
insert into dbo.PRODUCT_DESCRIPTIONS select PRODUCT_ID,LANGUAGE_ID,TRANSLATED_NAME,TRANSLATED_DESCRIPTION from dbo.PRODUCT_DESCRIPTIONS_External;
insert into dbo.PRODUCT_INFORMATION select PRODUCT_ID,PRODUCT_NAME,CATEGORY_ID,WEIGHT_CLASS,WARRANTY_PERIOD,SUPPLIER_ID,PRODUCT_STATUS,LIST_PRICE,MIN_PRICE, CATALOG_URL from  dbo.PRODUCT_INFORMATION_External;
insert into dbo.ORDERS select ORDER_ID,ORDER_DATE,ORDER_MODE,CUSTOMER_ID,ORDER_STATUS,ORDER_TOTAL,SALES_REP_ID,PROMOTION_ID from dbo.ORDERS_External;
insert into dbo.ORDER_ITEMS select ORDER_ID,LINE_ITEM_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY from dbo.ORDER_ITEMS_External;
insert into dbo.INVENTORIES select PRODUCT_ID,WAREHOUSE_ID,QUANTITY_ON_HAND from dbo.INVENTORIES_External;

select count(*) from dbo.LOCATIONS UNION ALL
select count(*) from dbo.JOBS  UNION ALL
select count(*) from dbo.EMPLOYEES  UNION ALL
select count(*) from dbo.DEPARTMENTS UNION ALL
select count(*) from dbo.COUNTRIES  UNION ALL
select count(*) from dbo.PROMOTIONS UNION ALL
select count(*) from dbo.PRODUCT_DESCRIPTIONS UNION ALL
select count(*) from dbo.PRODUCT_INFORMATION UNION ALL
select count(*) from dbo.ORDERS UNION ALL
select count(*) from dbo.ORDER_ITEMS UNION ALL
select count(*) from dbo.INVENTORIES;


select 'LOCATIONS' , (SELECT COUNT(*) FROM dbo.locations) ASIS_CNT, 'LOCATIONS_EXTERNAL' , (SELECT COUNT(*) FROM dbo.LOCATIONS_EXTERNAL) TOBE_CNT UNION ALL
select 'JOBS' , (SELECT COUNT(*) FROM dbo.JOBS) ASIS_CNT, 'JOBS_EXTERNAL' , (SELECT COUNT(*) FROM dbo.JOBS_EXTERNAL) TOBE_CNT UNION ALL
select 'EMPLOYEES' , (SELECT COUNT(*) FROM dbo.EMPLOYEES) ASIS_CNT, 'EMPLOYEES_EXTERNAL' , (SELECT COUNT(*) FROM dbo.EMPLOYEES_EXTERNAL) TOBE_CNT UNION ALL
select 'DEPARTMENTS' , (SELECT COUNT(*) FROM dbo.DEPARTMENTS) ASIS_CNT, 'DEPARTMENTS_EXTERNAL' , (SELECT COUNT(*) FROM dbo.DEPARTMENTS_EXTERNAL) TOBE_CNT UNION ALL
select 'COUNTRIES' , (SELECT COUNT(*) FROM dbo.COUNTRIES) ASIS_CNT, 'COUNTRIES_EXTERNAL' , (SELECT COUNT(*) FROM dbo.COUNTRIES_EXTERNAL) TOBE_CNT UNION ALL
select 'PROMOTIONS' , (SELECT COUNT(*) FROM dbo.PROMOTIONS) ASIS_CNT, 'PROMOTIONS_EXTERNAL' , (SELECT COUNT(*) FROM dbo.PROMOTIONS_EXTERNAL) TOBE_CNT UNION ALL
select 'PRODUCT_DESCRIPTIONS' , (SELECT COUNT(*) FROM dbo.PRODUCT_DESCRIPTIONS) ASIS_CNT, 'PRODUCT_DESCRIPTIONS_EXTERNAL' , (SELECT COUNT(*) FROM dbo.PRODUCT_DESCRIPTIONS_EXTERNAL) TOBE_CNT UNION ALL
select 'PRODUCT_INFORMATION' , (SELECT COUNT(*) FROM dbo.PRODUCT_INFORMATION) ASIS_CNT, 'PRODUCT_INFORMATION_EXTERNAL' , (SELECT COUNT(*) FROM dbo.PRODUCT_INFORMATION_EXTERNAL) TOBE_CNT UNION ALL
select 'ORDERS' , (SELECT COUNT(*) FROM dbo.ORDERS) ASIS_CNT, 'ORDERS_EXTERNAL' , (SELECT COUNT(*) FROM dbo.ORDERS_EXTERNAL) TOBE_CNT UNION ALL
select 'ORDER_ITEMS' ,  (SELECT COUNT(*) FROM dbo.ORDER_ITEMS) ASIS_CNT,   'ORDER_ITEMS_EXTERNAL' , (SELECT COUNT(*) FROM dbo.ORDER_ITEMS_EXTERNAL) TOBE_CNT UNION ALL
select 'INVENTORIES' , (SELECT COUNT(*) FROM dbo.INVENTORIES) ASIS_CNT,  'INVENTORIES_EXTERNAL' , (SELECT COUNT(*) FROM dbo.INVENTORIES_EXTERNAL) TOBE_CNT